### ISSUE TITLE
Hiccups in Kata2 Step 3

### ISSUE THREAD

**Issue by Dave-Poole-60103** [goldmansachs/obevo#157]
### Expected Behavior
Kata2 Step 3 should deploy to the HSQL obevokata database on localhost:9092

### Actual Behavior
The schema MYLARGESCHEMA_DEV1 deploys but has no contents and the error message suggests that it cannot interpret the file path that include localhost:9092.

Renaming `hsql/localhost:9092` to `hsql/localhost` allows deployment to take place

The exception is as follows: -
```
*** Exception stack trace ***
com.gs.obevo.util.vfs.VFSFileSystemException: org.apache.commons.vfs2.FileSystemException: Could not find files in "file:///Users/my.user/code/obevo-kata/reverse-engineering-example/final".
	at com.gs.obevo.util.vfs.FileObject.findFiles(FileObject.java:224)
	at com.gs.obevo.impl.DisabledOnboardingStrategy.validateSourceDirs(DisabledOnboardingStrategy.java:53)
	at com.gs.obevo.impl.MainDeployer.executeInternal(MainDeployer.java:158)
	at com.gs.obevo.impl.MainDeployer.execute(MainDeployer.java:109)
	at com.gs.obevo.impl.context.AbstractDeployerAppContext.deploy(AbstractDeployerAppContext.java:147)
	at com.gs.obevo.db.cmdline.DbDeployerMain.start(DbDeployerMain.java:73)
	at com.gs.obevo.cmdline.AbstractMain.start(AbstractMain.java:124)
	at com.gs.obevo.dist.Main$3.value(Main.java:176)
	at com.gs.obevo.dist.Main$3.value(Main.java:173)
	at com.gs.obevo.dist.Main.execute(Main.java:115)
	at com.gs.obevo.dist.Main.execute(Main.java:83)
	at com.gs.obevo.dist.Main.main(Main.java:70)
Caused by: org.apache.commons.vfs2.FileSystemException: Could not find files in "file:///Users/my.user/code/obevo-kata/reverse-engineering-example/final".
	at org.apache.commons.vfs2.provider.AbstractFileObject.findFiles(AbstractFileObject.java:1700)
	at org.apache.commons.vfs2.provider.AbstractFileObject.findFiles(AbstractFileObject.java:1198)
	at com.gs.obevo.util.vfs.FileObject.findFiles(FileObject.java:221)
	... 11 common frames omitted
Caused by: org.apache.commons.vfs2.FileSystemException: Invalid descendent file name "localhost:9092".
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveName(DefaultFileSystemManager.java:791)
	at org.apache.commons.vfs2.provider.AbstractFileObject.getChildren(AbstractFileObject.java:710)
	at org.apache.commons.vfs2.provider.AbstractFileObject.traverse(AbstractFileObject.java:1724)
	at org.apache.commons.vfs2.provider.AbstractFileObject.traverse(AbstractFileObject.java:1729)
	at org.apache.commons.vfs2.provider.AbstractFileObject.findFiles(AbstractFileObject.java:1695)
	... 13 common frames omitted
```

### Obevo Version where this issue was observed
6.5.0

### Steps to reproduce the behavior

I followed the steps on the Kata.  I'm using a MacBook

**Comment by shantstepanian** [comment]
I am unable to reproduce the issue as you mentioned. I am also on a MacBook

Can you please let me know:

* Which file is having "localhost:9092" in its name? That should only be in the JDBC URL value, not the file name
* The full text content of the command you deployed?
* Where you had to do the rename from hsql/localhost:9092 to hsql/localhost

(I should be able to reply sooner tomorrow during the day; I will have my laptop on me)

**Comment by Dave-Poole-60103** [comment]
Following the Kata I ended up with the following file structure within the reverse-engineering-example folder.
```
final
...MYLARGESCHEMA
......sp
......table
......usertype
......view
...hsql
......localhost:9092  -- This is the one I renamed to **localhost**
hsql
...localhost:9092
interim
```
The structure was produced by running
```$OBEVO_HOME/bin/deploy.sh NEWREVENG -mode SCHEMA -dbType HSQL -jdbcUrl jdbc:hsqldb:hsql://localhost:9092/obevokata -dbSchema MYLARGESCHEMA -username katadeployer -password katadeploypass -outputPath $KATA_HOME/reverse-engineering-example```

The error message was thrown when calling the following command.
```$OBEVO_HOME/bin/deploy.sh PREVIEW -sourcePath $KATA_HOME/reverse-engineering-example/final -env dev1 -deployUserId katadeployer -password katadeploypass```

I will wipe the environment and try again.

**Comment by Dave-Poole-60103** [comment]
I wiped the environment and started Kata2 from scratch and no errors were detected.  It functioned as intended.

I believe this may have been a PEBCAK error (problem exists between chair and keyboard) with the cause being a mistyping of the dev1 JDBC connection string causing the creation of the localhost:9092 folder.

**Comment by shantstepanian** [comment]
No problem. Thanks for the details; good to have in case someone else runs into this, and I'll try to reproduce it if I get a couple mins.

Feel free to reach out if you run into any other issues
