### ISSUE TITLE
UTF8 DDL scripts

### ISSUE THREAD

**Issue by stasmir** [goldmansachs/obevo#165]
Hi,

We're trying to use Obevo, but encountered a problem with UTF8 encoding.
I've successfully generated DDL scripts by using the Powershell command: ` SqlServerDdlReveng ***args***` 
But Obevo cannot process them.
Invoking a command:
`H:\obevo-dist\bin>deploy.bat newreveng -dbType MSSQL -mode SCHEMA -outputPath H:\Master -username *** -password *** -dbSchema *** -inputPath H:\Master`
causes the following output:                                                                
```
[INFO] c.g.o.d.Main [main] [3-26 15:41:48] - Starting action at time [Mon Mar 26 15:41:48 GMT+03:00 2018]
[INFO] o.a.c.v.i.StandardFileSystemManager [main] [3-26 15:41:49] - Using "C:\Windows\TEMP\vfs_cache" as temporary files store.
[WARN] c.g.o.a.f.PlatformConfigReader [main] [3-26 15:41:49] - Warnings on platform configuration file setup; please address in the future, but program will proceed:
File name [default.properties] was found in multiple locations [[jar:file:///H:/obevo-dist/lib/obevo-db-6.5.2.jar!/com/gs/obevo/db/config/default.properties, jar:file:///H:/obevo-dist/lib/obevo-core-6.5.2.jar!/com/gs/obevo/config/default.properties]]. Will refer to them in their priority order, but ideally the file name should be different.
[WARN] c.g.o.a.f.PlatformConfigReader [main] [3-26 15:41:49] - Warnings on platform configuration file setup; please address in the future, but program will proceed:
File name [default.properties] was found in multiple locations [[jar:file:///H:/obevo-dist/lib/obevo-db-6.5.2.jar!/com/gs/obevo/db/config/default.properties, jar:file:///H:/obevo-dist/lib/obevo-core-6.5.2.jar!/com/gs/obevo/config/default.properties]]. Will refer to them in their priority order, but ideally the file name should be different.
[INFO] c.g.o.u.ArgsParser [main] [3-26 15:41:49] - Arguments parsed: AquaRevengArgs [inputPath=H:\Master, outputPathH:\Master, tablespaceToken=false, tokenizeDefaultSchema=false, generateBaseline=false, dbPlatform=com.gs.obevo.db.impl.platforms.mssql.MsSqlDbPlatform@723e88f9, dbPort=null, dbSchema=***, username=***, mode=SCHEMA, preprocessSchemaTokens=true]
[INFO] c.g.o.d.Main [main] [3-26 15:41:50] - 
[INFO] c.g.o.d.Main [main] [3-26 15:41:50] - Action completed with errors at Mon Mar 26 15:41:50 GMT+03:00 2018, took 2 seconds.
[INFO] c.g.o.d.Main [main] [3-26 15:41:50] - 
[INFO] c.g.o.d.Main [main] [3-26 15:41:50] - *** Exception stack trace ***
com.gs.obevo.db.sqlparser.tokenparser.TokenMgrError: Lexical error at line 1, column 1.  Encountered: "\u043f" (1087), after : ""
	at com.gs.obevo.db.sqlparser.tokenparser.SqlTokenParserImplTokenManager.getNextToken(SqlTokenParserImplTokenManager.java:717)
	at com.gs.obevo.db.sqlparser.tokenparser.SqlTokenParserImpl.getNextToken(SqlTokenParserImpl.java:108)
	at com.gs.obevo.db.sqlparser.tokenparser.SqlTokenParser.parseTokens(SqlTokenParser.java:36)
	at com.gs.obevo.impl.util.MultiLineStringSplitter.valueOf(MultiLineStringSplitter.java:83)
	at com.gs.obevo.db.apps.reveng.AbstractDdlReveng.getSqlSnippets(AbstractDdlReveng.java:516)
	at com.gs.obevo.db.apps.reveng.AbstractDdlReveng.access$000(AbstractDdlReveng.java:64)
	at com.gs.obevo.db.apps.reveng.AbstractDdlReveng$5.valueOf(AbstractDdlReveng.java:243)
	at com.gs.obevo.db.apps.reveng.AbstractDdlReveng$5.valueOf(AbstractDdlReveng.java:240)
	at org.eclipse.collections.impl.utility.internal.InternalArrayIterate.collect(InternalArrayIterate.java:446)
	at org.eclipse.collections.impl.list.mutable.FastList.collect(FastList.java:840)
	at org.eclipse.collections.impl.list.mutable.FastList.collect(FastList.java:706)
	at org.eclipse.collections.impl.list.mutable.FastList.collect(FastList.java:109)
	at com.gs.obevo.db.apps.reveng.AbstractDdlReveng.revengMain(AbstractDdlReveng.java:240)
	at com.gs.obevo.db.apps.reveng.AbstractDdlReveng.reveng(AbstractDdlReveng.java:183)
	at com.gs.obevo.dist.Main$5.value(Main.java:199)
	at com.gs.obevo.dist.Main$5.value(Main.java:194)
	at com.gs.obevo.dist.Main.execute(Main.java:115)
	at com.gs.obevo.dist.Main.execute(Main.java:83)
	at com.gs.gsobevo.dist.Main.main(Main.java:11)
[INFO] c.g.o.d.Main [main] [3-26 15:41:51] - 
[INFO] c.g.o.d.Main [main] [3-26 15:41:51] - Detailed Log File is available at: C:\Windows\TEMP\obevo-***5277197619962289650/obevo-newreveng-20180326154148.log
[INFO] c.g.o.d.Main [main] [3-26 15:41:51] - 
[INFO] c.g.o.d.Main [main] [3-26 15:41:51] - Exiting with errors!
```
If I convert DDL scripts into ANSI encoding the command proceeds successfully.

It's a problem because our scripts contain Cyrillic characters, so we need to have UTF8 encoding for our DDL scripts.

**Comment by shantstepanian** [comment]
Hi, I have an idea around the fix. We will look to release a patch soon
