### ISSUE TITLE
Windows 10 charset and Reverse Engineering

### ISSUE THREAD

**Issue by paulkatich** [goldmansachs/obevo#236]
For bugs/errors, please provide the following if feasible:
* Description of problem
Please see below.
* Steps to reproduce the issue (e.g. the commands that you ran)
Run the reveng process
* Any DDLs/code to help reproduce the issue
The process fails while generating the interim folder sql.
* Logs/stack traces for exceptions
Please see below.
* Obevo version you were on (I will assume the latest released version if not specified)
Latest snapshot version.

I am running reverse engineering on windows 10. Looks the oracle kotlin reveng uses the Charset.defaultCharset(). This might be the platform default charset. I had a failure on a schema. I was able to resolve it using UTF-8. Let me know if I can do a pull request for changing charset. 

Action completed with errors at Fri May 24 09:27:06 EDT 2019, took 105 seconds.

*** Exception stack trace ***
java.nio.charset.UnmappableCharacterException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:285)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
        at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
        at java.io.BufferedWriter.write(BufferedWriter.java:230)
        at java.io.Writer.write(Writer.java:157)
        at com.gs.obevo.db.impl.platforms.oracle.OracleReveng.doRevengOrInstructions(OracleReveng.kt:106)
        at com.gs.obevo.db.apps.reveng.AbstractDdlReveng.reveng(AbstractDdlReveng.java:164)
        at com.gs.obevo.dist.Main$7.value(Main.java:208)
        at com.gs.obevo.dist.Main$7.value(Main.java:203)
        at com.gs.obevo.dist.Main.execute(Main.java:119)
        at com.gs.obevo.dist.Main.execute(Main.java:87)
        at com.gs.obevo.dist.Main.main(Main.java:69)
        Suppressed: java.nio.charset.UnmappableCharacterException: Input length = 1
                at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
                at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:285)
                at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
                at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
                at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
                at java.io.BufferedWriter.close(BufferedWriter.java:265)
                at kotlin.io.CloseableKt.closeFinally(Closeable.kt:56)
                at com.gs.obevo.db.impl.platforms.oracle.OracleReveng.doRevengOrInstructions(OracleReveng.kt:76)
                ... 6 common frames omitted

**Comment by shantstepanian** [comment]
Hi, I'm open to taking pull requests. I'm not clear what change you are requesting (i.e. whether to change the default used, or to allow the charset to be parametrizable by command line); you can submit the pull request if it helps to clarify that

In terms of getting the merge request accepted, you'll have to fill out a DCO, per the [contribution guide](https://github.com/goldmansachs/obevo/blob/master/CONTRIBUTING.md). You can see an example at the kata project (see [the DCO](https://github.com/goldmansachs/obevo-kata/tree/master/dco) and [the commit that was done by that developer](https://github.com/goldmansachs/obevo-kata/pull/6/files)). But we can do those steps once agreeing on the change to be made

**Comment by shantstepanian** [comment]
Hi, let me know if you'd like to submit a pull request, or if you just want to point me to the file + line number where you think the change is required. Also for my use case, where was the UTF character: in the object name or the object definition?

**Comment by gopalramadugu** [comment]
ok I will be submitting the change request. Can I please know what should the change number in the change log be ?  Please see below example what does 231 and 233 mean ?


EX: #231 #233: Correct reverse-engineering of table indices to their correct tables

**Comment by shantstepanian** [comment]
Those correspond to the pull request # and/or the issue # that corresponded to the ticket. You can click the #231 link in the comment as an example
As you haven't created the pull request yet, you may not have the number yet for that (though I've can infer it). Given that we already have a ticket number for this, you can just add the number for this issue #236

**Comment by gopalramadugu** [comment]
Thank you Submitted a pull requested.

**Comment by shantstepanian** [comment]
I made a minor change on the pom (a change that should have been there previously) and merged in your pull request. Thanks!

Fyi - per the dco, I added "covered by: gopal_ramadugu.dco" to your commit message

**Comment by shantstepanian** [comment]
Snapshot has been published based on your change - https://github.com/goldmansachs/obevo/releases/download/master-SNAPSHOT/obevo-cli-master-SNAPSHOT-dist.zip

**Comment by gopalramadugu** [comment]
@shantstepanian I dont see the obevo-cli-dist.zip on the releases page. Can you please look in to this ?

**Comment by shantstepanian** [comment]
This will need a couple days. The build failed as IBM changed the location of its DB2 Container on Dockerhub

**Comment by shantstepanian** [comment]
DB2 issue is fixed. Will perform the release once your other tickets are resolved
