### ISSUE TITLE
Reverse engineering an Oracle database crashes on index partitions

### ISSUE THREAD

**Issue by kartsm** [goldmansachs/obevo#246]
#  Description of problem

When attempting to reverse engineer an existing schema in Oracle that uses index partitions, the reverse engineering process quits with this error:

```
com.gs.obevo.db.impl.core.jdbc.DataAccessException: java.sql.SQLException: ORA-31600: invalid input value INDEX_PARTITION for parameter OBJECT_TYPE in function GET_DDL
ORA-06512: at "SYS.DBMS_METADATA", line 5805
ORA-06512: at "SYS.DBMS_METADATA", line 8344
ORA-06512: at line 1
```

No output is produced in the designated `-outputPath` directory.

# Steps to reproduce the issue (e.g. the commands that you ran)

Some names have been changed to protect the innocent 😇 

```
jdbcurl='jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=ON)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=REDACTED)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=REDACTED)(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC))))'
schema=REDACTED
password=REDACTED
$OBEVO_HOME/bin/deploy.sh newreveng \
        -dbType ORACLE \
        -dbSchema "$schema" \
        -mode schema \
        -outputPath "$PWD/src/main/database/${schema}/reveng" \
        -jdbcUrl "$jdbcurl" \
        -username "$schema" \
        -password "$password" \
        2>&1 | tee reveng_${schema}_$(date +%Y%m%d_%H%M%S).log
```

# Any DDLs/code to help reproduce the issue

While I don't know which object in particular tripped up the reverse-engineer, I can offer this from the database schema in question:

```
SQL> select object_type, count(object_name) from user_objects group by object_type;

OBJECT_TYPE         COUNT(OBJECT_NAME)
------------------- ------------------
INDEX PARTITION                    491
SEQUENCE                           757
TABLE PARTITION                    184
PROCEDURE                           14
LOB PARTITION                        5
DATABASE LINK                        1
PACKAGE                            225
PACKAGE BODY                       225
LOB                                 43
TYPE BODY                            1
TRIGGER                            385

OBJECT_TYPE         COUNT(OBJECT_NAME)
------------------- ------------------
INDEX                             4423
FUNCTION                            12
SYNONYM                              6
TABLE                             2628
JAVA SOURCE                          1
JAVA CLASS                           1
VIEW                              1972
TYPE                                 4

19 rows selected.
```

The database in question is currently on Oracle 11.2.0.4.0.  While reverse-engineering I was using `ojdbc6-11.2.0.4.0.jar` from the Oracle 11.2 instant client distribution, with this JRE:

```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

On a server running:

```
$ uname -a
Linux REDACTED 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 15 17:36:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

I also tried with  `ojdbc8-19.3.0.0.0.jar` from Oracle 19.3 instant client, and got identical results.  

# Logs/stack traces for exceptions

```
Starting action at time [Wed Jul 24 13:23:13 EDT 2019]
Using "/tmp/vfs_cache" as temporary files store.
Arguments parsed: AquaRevengArgs [outputPath/home/tony.monroe/src/obevo-kata/src/main/database/REDACTED/reveng, tablespaceToken=false, tokenizeDefaultSchema=false, generateBaseline=false, dbPlatform=com.gs.obevo.db.impl.platforms.oracle.OracleDbPlatform@22f31dec, dbPort=null, dbSchema=REDACTED, username=REDACTED, mode=SCHEMA, preprocessSchemaTokens=true]


Action completed with errors at Wed Jul 24 13:24:14 EDT 2019, took 61 seconds.

*** Exception stack trace ***
com.gs.obevo.db.impl.core.jdbc.DataAccessException: java.sql.SQLException: ORA-31600: invalid input value INDEX_PARTITION for parameter OBJECT_TYPE in function GET_DDL
ORA-06512: at "SYS.DBMS_METADATA", line 5805
ORA-06512: at "SYS.DBMS_METADATA", line 8344
ORA-06512: at line 1

        at com.gs.obevo.db.impl.core.jdbc.JdbcHelper.query(JdbcHelper.java:175)
        at com.gs.obevo.db.impl.core.jdbc.JdbcHelper.queryForList(JdbcHelper.java:225)
        at com.gs.obevo.db.impl.platforms.oracle.OracleReveng.doRevengOrInstructions(OracleReveng.kt:127)
        at com.gs.obevo.db.apps.reveng.AbstractDdlReveng.reveng(AbstractDdlReveng.java:165)
        at com.gs.obevo.dist.Main$7.value(Main.java:208)
        at com.gs.obevo.dist.Main$7.value(Main.java:203)
        at com.gs.obevo.dist.Main.execute(Main.java:119)
        at com.gs.obevo.dist.Main.execute(Main.java:87)
        at com.gs.obevo.dist.Main.main(Main.java:69)
```

# Obevo version 

7.1.0

# Resolution

After getting a clone of the latest source, applying the following patch on the `master` branch, building with `mvn clean package`, and using the resulting `obevo-cli-local-SNAPSHOT-dist.zip`, the reverse-engineer ran to completion.

```diff
diff --git a/obevo-db-impls/obevo-db-oracle/src/main/java/com/gs/obevo/db/impl/platforms/oracle/OracleReveng.kt b/obevo-db-impls/obevo-db-oracle/src/main/java/com/gs/obevo/db/impl/platforms/oracle/OracleReveng.kt
index 91fd993..6927ac5 100644
--- a/obevo-db-impls/obevo-db-oracle/src/main/java/com/gs/obevo/db/impl/platforms/oracle/OracleReveng.kt
+++ b/obevo-db-impls/obevo-db-oracle/src/main/java/com/gs/obevo/db/impl/platforms/oracle/OracleReveng.kt
@@ -184,7 +184,7 @@ LEFT JOIN DBA_TABLES tab ON obj.OBJECT_TYPE = 'TABLE' AND obj.OWNER = tab.OWNER
 LEFT JOIN MY_CONSTRAINT_INDICES conind ON obj.OBJECT_TYPE = 'INDEX' AND obj.OWNER = conind.INDEX_OWNER AND obj.OBJECT_NAME = conind.INDEX_NAME
 WHERE obj.OWNER = '${schema}'
     AND obj.GENERATED = 'N'  -- do not include generated objects
-    AND obj.OBJECT_TYPE NOT IN ('PACKAGE BODY', 'LOB', 'TABLE PARTITION', 'DATABASE LINK')
+    AND obj.OBJECT_TYPE NOT IN ('PACKAGE BODY', 'LOB', 'TABLE PARTITION', 'DATABASE LINK', 'INDEX PARTITION')
     AND obj.OBJECT_NAME NOT LIKE 'MLOG${'$'}%' AND obj.OBJECT_NAME NOT LIKE 'RUPD${'$'}%'  -- exclude the helper tables for materialized views
     AND obj.OBJECT_NAME NOT LIKE 'SYS_%'  -- exclude other system tables
     AND conind.INDEX_OWNER IS NULL  -- exclude primary keys created as unique indexes, as the CREATE TABLE already includes it; SQL logic is purely in the join above
```

**Comment by shantstepanian** [comment]
Thanks for the detailed explanation

In terms of identifying the problematic object - can you try the latest snapshot version (https://github.com/goldmansachs/obevo/releases/download/master-SNAPSHOT/obevo-cli-master-SNAPSHOT-dist.zip) and rerun your reverse-engineering? That has a fix to avoid crashing if a single object has an issue; you can then search for "OBEVO EXCEPTION" within the generated files to find the problematic object

I'll then apply your suggested fix along w/ test cases

**Comment by kartsm** [comment]
I'll try with the recommended snapshot today; hopefully it won't take too long.

**Comment by kartsm** [comment]
Took longer than I expected, but it did finish!
```
Action completed successfully at Thu Jul 25 12:35:39 EDT 2019, took 5627 seconds.
```
Here is a summary of the places where an exception occurred:
```
$ grep -lr OBEVO.*EXCEPTION | xargs head -1
==> src/main/database/REDACTED/reveng/interim/output.sql <==


==> src/main/database/REDACTED/reveng/final/REDACTED/unableToClassify-pleaseAnalyze/IX8_REMARKETING_INVENTORY.sql <==
OBEVO EXCEPTION IX8_REMARKETING_INVENTORY of type INDEX PARTITION

==> src/main/database/REDACTED/reveng/final/REDACTED/unableToClassify-pleaseAnalyze/IX3_REMARKETING_INVENTORY.sql <==
OBEVO EXCEPTION IX3_REMARKETING_INVENTORY of type INDEX PARTITION

==> src/main/database/REDACTED/reveng/final/REDACTED/unableToClassify-pleaseAnalyze/IX1_REMARKETING_INVENTORY.sql <==
OBEVO EXCEPTION IX1_REMARKETING_INVENTORY of type INDEX PARTITION

==> src/main/database/REDACTED/reveng/final/REDACTED/unableToClassify-pleaseAnalyze/IX1_APPLICATION_EVENTS_DETAILS.sql <==
OBEVO EXCEPTION IX1_APPLICATION_EVENTS_DETAILS of type INDEX PARTITION

==> src/main/database/REDACTED/reveng/final/REDACTED/unableToClassify-pleaseAnalyze/IX1_APPLICATION_EVENTS.sql <==
OBEVO EXCEPTION IX1_APPLICATION_EVENTS of type INDEX PARTITION

==> src/main/database/REDACTED/reveng/final/REDACTED/unableToClassify-pleaseAnalyze/IX2_REMARKETING_INVENTORY.sql <==
OBEVO EXCEPTION IX2_REMARKETING_INVENTORY of type INDEX PARTITION
```
Taking a page from the Oracle manuals, I asked about the indexes and partitions of those names:
```
SQL> select index_name as "index or partition name", status from user_indexes where index_name in ('IX8_REMARKETING_INVENTORY', 'IX3_REMARKETING_INVENTORY', 'IX2_REMARKETING_INVENTORY', 'IX1_REMARKETING_INVENTORY', 'IX1_APPLICATION_EVENTS', 'IX1_APPLICATION_EVENT_DETAILS') union all select partition_name as "index or partition name", status from user_ind_partitions where partition_name like '%IX%_REMARKETING_INVENTORY%' or partition_name like '%IX1_APPLICATION_EVENTS%';

index or partition name        STATUS
------------------------------ --------
IX1_APPLICATION_EVENTS         N/A
IX1_REMARKETING_INVENTORY      N/A
IX2_REMARKETING_INVENTORY      N/A
IX3_REMARKETING_INVENTORY      N/A
IX8_REMARKETING_INVENTORY      N/A

SQL> select index_name as "index or partition name", status from user_indexes where status = 'N/A' union all select partition_name as "index or partition_name", status from user_ind_partitions where status = 'N/A';

index or partition name        STATUS
------------------------------ --------
IX1_APPLICATION_EVENTS_DETAILS N/A
IX1_APPLICATION_EVENTS         N/A
SYS_IL0001225743C00003$$       N/A
IX2_WATCHLIST_VEHICLES         N/A
IX5_WATCHLIST_VEHICLES         N/A
IX1_REMARKETING_INVENTORY      N/A
IX2_REMARKETING_INVENTORY      N/A
IX3_REMARKETING_INVENTORY      N/A
IX8_REMARKETING_INVENTORY      N/A
IX1_WATCHLIST_VEHICLES         N/A
```
I wonder if the `N/A` status explains why those objects weren't receptive to reverse engineering.

(Note: I am not a DBA, I'm mostly here for the automation.)

**Comment by shantstepanian** [comment]
Thanks. Can you show the full content of one of those files containing OBEVO EXCEPTION?

**Comment by kartsm** [comment]
[IX2_REMARKETING_INVENTORY.sql.txt](https://github.com/goldmansachs/obevo/files/3433085/IX2_REMARKETING_INVENTORY.sql.txt)

(Renamed to `.sql.txt` because drag-and-drop upload refuses `.sql`)

**Comment by shantstepanian** [comment]
I've committed the fix suggested here. I'm unable to test it with my local Docker Oracle instance, but I'll go w/ the suggestion nonetheless
