### ISSUE TITLE
Fix DB2 reorg exception detection

### ISSUE THREAD

**Issue by shantstepanian** [goldmansachs/obevo#49]

**Comment by shantstepanian** [comment]
Worth double-checking this particular exception stack trace. Also note that this was on obevo 5.x

com.ibm.db2.jcc.b.ni: [ibm][db2][jcc][102][10040] Non-atomic batch failure.  The batch was submitted, but at least one exception occurred on an individual member of the batch.
Use getNextException() to retrieve the exceptions for specific batched elements.
	at com.ibm.db2.jcc.b.p.a(p.java:414)
	at com.ibm.db2.jcc.b.ih.a(ih.java:2876)
	at com.ibm.db2.jcc.b.ih.b(ih.java:2710)
	at com.ibm.db2.jcc.b.ih.executeBatch(ih.java:1554)
	at com.gs.deployanywhere.db.impl.core.jdbc.JdbcHelper.batchUpdate(JdbcHelper.java:165)
	at com.gs.deployanywhere.db.impl.core.changetypes.CsvStaticDataDeployer.executeInserts(CsvStaticDataDeployer.java:346)
	at com.gs.deployanywhere.db.impl.core.changetypes.CsvStaticDataDeployer$2.run(CsvStaticDataDeployer.java:116)
	at com.gs.deployanywhere.db.impl.platforms.AbstractSqlExecutor.executeWithinContext(AbstractSqlExecutor.java:46)
	at com.gs.deployanywhere.db.impl.core.changetypes.CsvStaticDataDeployer.deployArtifact(CsvStaticDataDeployer.java:113)
	at com.gs.deployanywhere.db.impl.core.changetypes.StaticDataChangeTypeBehavior.deploy(StaticDataChangeTypeBehavior.java:69)
	at com.gs.deployanywhere.api.platform.ChangeTypeImpl.deploy(ChangeTypeImpl.java:93)
	at com.gs.deployanywhere.api.appdata.Change.deploy(Change.java:557)
	at com.gs.deployanywhere.impl.command.DeployChangeCommand.execute(DeployChangeCommand.java:17)
	at com.gs.deployanywhere.impl.ExecuteDeployStrategy.deploy(ExecuteDeployStrategy.java:19)
	at com.gs.deployanywhere.impl.MainDeployer.doExecute(MainDeployer.java:287)
	at com.gs.deployanywhere.impl.MainDeployer.executeInternal(MainDeployer.java:168)
	at com.gs.deployanywhere.impl.MainDeployer.execute(MainDeployer.java:92)
	at com.gs.deployanywhere.db.impl.core.DbDeployerAppContextImpl.deploy(DbDeployerAppContextImpl.java:488)
	at com.gs.deployanywhere.db.impl.core.DbDeployerAppContextImpl.deploy(DbDeployerAppContextImpl.java:73)
	at com.gs.deployanywhere.db.cmdline.DbDeployerMain.start(DbDeployerMain.java:66)
	at com.gs.deployanywhere.db.cmdline.DbDeployerMain.start(DbDeployerMain.java:21)
	at com.gs.deployanywhere.cmdline.DeployAnywhereMain.start(DeployAnywhereMain.java:111)
	at com.gs.deployanywhere.dist.Main.run(Main.java:105)
	at com.gs.deployanywhere.dist.Main.main(Main.java:65)

With Root Cause: com.ibm.db2.jcc.b.SqlException: Error for batch element #1: DB2 SQL error: SQLCODE: -668, SQLSTATE: 57016, SQLERRMC: 7;MYSCHEMA.MYTABLE
	at com.ibm.db2.jcc.c.db.a(db.java:450)
	at com.ibm.db2.jcc.c.db.a(db.java:68)
	at com.ibm.db2.jcc.c.t.a(t.java:59)
	at com.ibm.db2.jcc.c.tb.a(tb.java:207)
	at com.ibm.db2.jcc.b.ih.a(ih.java:1904)
	at com.ibm.db2.jcc.b.ih.b(ih.java:3033)
	at com.ibm.db2.jcc.b.ih.a(ih.java:2818)
	at com.ibm.db2.jcc.b.ih.b(ih.java:2710)
	at com.ibm.db2.jcc.b.ih.executeBatch(ih.java:1554)
	at com.gs.deployanywhere.db.impl.core.jdbc.JdbcHelper.batchUpdate(JdbcHelper.java:165)
	at com.gs.deployanywhere.db.impl.core.changetypes.CsvStaticDataDeployer.executeInserts(CsvStaticDataDeployer.java:346)
	at com.gs.deployanywhere.db.impl.core.changetypes.CsvStaticDataDeployer$2.run(CsvStaticDataDeployer.java:116)
	at com.gs.deployanywhere.db.impl.platforms.AbstractSqlExecutor.executeWithinContext(AbstractSqlExecutor.java:46)
	at com.gs.deployanywhere.db.impl.core.changetypes.CsvStaticDataDeployer.deployArtifact(CsvStaticDataDeployer.java:113)
	at com.gs.deployanywhere.db.impl.core.changetypes.StaticDataChangeTypeBehavior.deploy(StaticDataChangeTypeBehavior.java:69)
	at com.gs.deployanywhere.api.platform.ChangeTypeImpl.deploy(ChangeTypeImpl.java:93)
	at com.gs.deployanywhere.api.appdata.Change.deploy(Change.java:557)
	at com.gs.deployanywhere.impl.command.DeployChangeCommand.execute(DeployChangeCommand.java:17)
	at com.gs.deployanywhere.impl.ExecuteDeployStrategy.deploy(ExecuteDeployStrategy.java:19)
	at com.gs.deployanywhere.impl.MainDeployer.doExecute(MainDeployer.java:287)
	at com.gs.deployanywhere.impl.MainDeployer.executeInternal(MainDeployer.java:168)
	at com.gs.deployanywhere.impl.MainDeployer.execute(MainDeployer.java:92)
	at com.gs.deployanywhere.db.impl.core.DbDeployerAppContextImpl.deploy(DbDeployerAppContextImpl.java:488)
	at com.gs.deployanywhere.db.impl.core.DbDeployerAppContextImpl.deploy(DbDeployerAppContextImpl.java:73)
	at com.gs.deployanywhere.db.cmdline.DbDeployerMain.start(DbDeployerMain.java:66)
	at com.gs.deployanywhere.db.cmdline.DbDeployerMain.start(DbDeployerMain.java:21)
	at com.gs.deployanywhere.cmdline.DeployAnywhereMain.start(DeployAnywhereMain.java:111)
	at com.gs.deployanywhere.dist.Main.run(Main.java:105)
	at com.gs.deployanywhere.dist.Main.main(Main.java:65)

	at com.gs.deployanywhere.db.impl.core.jdbc.JdbcHelper.batchUpdate(JdbcHelper.java:169)
	at com.gs.deployanywhere.db.impl.core.changetypes.CsvStaticDataDeployer.executeInserts(CsvStaticDataDeployer.java:346)
	at com.gs.deployanywhere.db.impl.core.changetypes.CsvStaticDataDeployer$2.run(CsvStaticDataDeployer.java:116)
	at com.gs.deployanywhere.db.impl.platforms.AbstractSqlExecutor.executeWithinContext(AbstractSqlExecutor.java:46)
	at com.gs.deployanywhere.db.impl.core.changetypes.CsvStaticDataDeployer.deployArtifact(CsvStaticDataDeployer.java:113)
	at com.gs.deployanywhere.db.impl.core.changetypes.StaticDataChangeTypeBehavior.deploy(StaticDataChangeTypeBehavior.java:69)
	at com.gs.deployanywhere.api.platform.ChangeTypeImpl.deploy(ChangeTypeImpl.java:93)
	at com.gs.deployanywhere.api.appdata.Change.deploy(Change.java:557)
	at com.gs.deployanywhere.impl.command.DeployChangeCommand.execute(DeployChangeCommand.java:17)
	at com.gs.deployanywhere.impl.ExecuteDeployStrategy.deploy(ExecuteDeployStrategy.java:19)
	at com.gs.deployanywhere.impl.MainDeployer.doExecute(MainDeployer.java:287)
	at com.gs.deployanywhere.impl.MainDeployer.executeInternal(MainDeployer.java:168)
	at com.gs.deployanywhere.impl.MainDeployer.execute(MainDeployer.java:92)
	at com.gs.deployanywhere.db.impl.core.DbDeployerAppContextImpl.deploy(DbDeployerAppContextImpl.java:488)
	at com.gs.deployanywhere.db.impl.core.DbDeployerAppContextImpl.deploy(DbDeployerAppContextImpl.java:73)
	at com.gs.deployanywhere.db.cmdline.DbDeployerMain.start(DbDeployerMain.java:66)
	at com.gs.deployanywhere.db.cmdline.DbDeployerMain.start(DbDeployerMain.java:21)
	at com.gs.deployanywhere.cmdline.DeployAnywhereMain.start(DeployAnywhereMain.java:111)
	at com.gs.deployanywhere.dist.Main.run(Main.java:105)
	at com.gs.deployanywhere.dist.Main.main(Main.java:65)
Caused by: com.ibm.db2.jcc.b.ni: [ibm][db2][jcc][102][10040] Non-atomic batch failure.  The batch was submitted, but at least one exception occurred on an individual member of the batch.
Use getNextException() to retrieve the exceptions for specific batched elements.
	at com.ibm.db2.jcc.b.p.a(p.java:414)
	at com.ibm.db2.jcc.b.ih.a(ih.java:2876)
	at com.ibm.db2.jcc.b.ih.b(ih.java:2710)
	at com.ibm.db2.jcc.b.ih.executeBatch(ih.java:1554)
	at com.gs.deployanywhere.db.impl.core.jdbc.JdbcHelper.batchUpdate(JdbcHelper.java:165)
	... 19 more

**Comment by shantstepanian** [comment]
Another string example:

com.ibm.db2.jcc.am.SqlException: DB2 SQL Error: SQLCODE=-668, SQLSTATE=57016, SQLERRMC=7;MYSCHEMA.MYTABLE, DRIVER=3.59.81
